name: bark-detector
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.24
  - scipy>=1.10
  - pyaudio>=0.2.13
  - influxdb-client>=1.36
  - redis-py>=5.0
  - requests>=2.31
  - pip
  - pip:
      - tflite-runtime>=2.14
